### ISSUE TITLE
does it have fix for sound delay when windows is left idle

### ISSUE THREAD

**Issue by vivekkpatel** [PyroCalzone/MechVibesPlusPlus#10]
this issue 
https://github.com/hainguyents13/mechvibes/issues/229

**Comment by PyroCalzone** [comment]
Are you asking a question or reporting an issue? I've never encountered this and I've never seen someone complain about this.

**Comment by vivekkpatel** [comment]
asking question.
I've encounter this issue with mechvibes. Did you use same build for MechvibesPlusPlus? I don't know what's difference between two software

**Comment by PyroCalzone** [comment]
Sorta, I've implemented a bunch more features and bug fixes. I've also enabled more diagnostic tools for bug reporting. Again, I've never encountered or heard of a bug like this though. Feel free to download and test yourself, and then create a new issue with the devtools log if you do find anything out of the ordinary.

**Comment by vivekkpatel** [comment]
already download, will use it for 1-2 weeks to see if see any issue happen. 
Bythe way during installation some error appeared. I just ignore it and continue with installation.
I think error was regarding Microsoft visual  Redistributable

**Comment by PyroCalzone** [comment]
If you already have Microsoft Visual C++ 2015-2019 installed, you should be fine.
