### ISSUE TITLE
Add linux build instructions

### ISSUE THREAD

**Issue by 0A7V9A** [PyroCalzone/MechVibesPlusPlus#2]
There's no instructions to build mechvibesplusplus in linux distros

**Comment by SaturnXOffical** [comment]
I've tried multiple times to build it myself using Ubuntu, elementaryOS, and Linux Mint. I think there needs to be some code revisions, if you really want the instructions then add me on discord. SaturnDev#0001

**Comment by PyroCalzone** [comment]
I don't have a machine to run Linux on, thus I cannot bug fix. To attempt to build yourself, go to the original mechvibes and copy their code, then replace their src folder with ours. then build it through electron for linux.

**Comment by 0A7V9A** [comment]
it did work!
