### ISSUE TITLE
Mouse Wheel Spin Sound

### ISSUE THREAD

**Issue by 0A7V9A** [PyroCalzone/MechVibesPlusPlus#3]
Hey,
I was thinking about mouse wheel spin sound. It would be great if this feature's added.
Thanks

**Comment by PyroCalzone** [comment]
We found that this feature sounds really bad typically, due to the spammy nature of a mouse wheel spin. Trying to play audio would ruin the experience. You are welcome to fork and create your own soundpack for it.
