### ISSUE TITLE
Severe Input Lag In Games

### ISSUE THREAD

**Issue by DefaultUser9148** [PyroCalzone/MechVibesPlusPlus#5]
So i did some tests and MechvibesPlusPlus causes Severe Input Lag in every steam and non steam game there is
I dont know what is causing is but i always have to kill Mechvibes to play games if i dont want to get annoyed at the input lag

---------------------
If you need any info
please reply to this comment

**Comment by DefaultUser9148** [comment]
Device:
Device name	Huawei_Matebook
Processor	Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz   2.59 GHz
Installed RAM	8,00 GB (7,84 GB usable)
Device ID	91876DE3-0BFF-456D-909A-FDD64C7F6258
Product ID	00325-82052-41484-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input available for this display

**Comment by PyroCalzone** [comment]
When running a game, with mechvibes++ open, can you send a picture of your task manager? I suspect you are maxing your resources out.

**Comment by ghost** [comment]
I normally set the affinity of my games to only one cpu / gpu when playing

**Comment by ghost** [comment]
That fixes it btw for me btw.

**Comment by PyroCalzone** [comment]
Well, if that fixes it.
